<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="HelloIndia"
     targetNamespace="http://xmlns.oracle.com/January2023Practice/HelloIndia/HelloIndia"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
     xmlns:bpws="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
     xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
     xmlns:tns="http://xmlns.oracle.com/January2023Practice/HelloIndia/HelloIndia"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
    <plnk:partnerLinkType name="HelloIndiaSOAPService">
        <plnk:role name="HelloPort" portType="tns:HelloPort"/>
    </plnk:partnerLinkType>
    <wsdl:import namespace="http://xmlns.oracle.com/January2023Practice/HelloIndia/HelloIndia" location="HelloIndia.wsdl"/>
</wsdl:definitions>
